### ISSUE TITLE
Help with panel plots

### ISSUE THREAD

**Issue by caitlintwhite** [caitlintwhite/KelmanProject#12]
ctw copying 2/27 email from Emily to julie and i:

I'm working on creating those panel plots - one with spei12 and CWM of the traits at each transect, and then another that includes the lagged spei12 and those same CWM traits. I'm struggling a bit to figure out how to create a panel plot which includes all the individual transect level data. I think the code would look something like this: 

testfig <- ggplot(subset( CWM_figures, trait_name%in% c("final_height_cm", "RMR", "SLA", "RDMC", "seed_mass")), mapping = aes(x=spei_12, y=value))+
  geom_line()+
  geom_point(size = 0.5)+
  geom_point(aes(col=transect_ID))

I know this isn't quite right, and I was wondering if either of you had any pointers. In the meantime, I am working on creating the panel plots for CWV of the traits and spei12 (current and lagged) using the pooled data.

**Comment by caitlintwhite** [comment]
@emilykelman You could combine the two geom_point statements in one: geom_point(aes(col = transect_ID), size = 0.5)

I'm not sure why the plot wouldn't at least color points by transect ID (the line wouldn't be colored because there is no color defined in the aesthetics there). (I would also not connect the points with a line because that's going to look very busy and may be hard to see where lines are going). 

Is transect_ID for sure in your CWM_figures data table? Is it named something else?

**Comment by julieelarson** [comment]
Hi Emily,

Where are you at with this? I'm curious whether you are getting a figure to show up at all, or if there is some error where it won't even display anything?

Here are some points:
1)  I agree with Caitlin about consolidating geom_point
2) I also agree about not using geom_line.  Remember, geom_line will just connect the dots, and what you really want is similar to the first set of figures you made showing all the transects-- a line of best fit (basically showing the different slopes for the different transects). You can go back into your exploratory code to remember how we did this, but here's what I'd try to start:
 
+ geom_smooth(method = "lm", col=transect_ID)

3) Don't forget that if you want this to show up as a panel plot, you need another line of code that tells ggplot to facet-wrap or facet-grid... without this, it might not know how to handle all of the traits your plugging in (put them all on the same figure? or...) 
Going back to your exploratory code again, I've copied a line below that will get you started.. you'll want to add something like this to your block of ggplot code

+ facet_grid(trait_name~., scales = "free_y")


Let us know how it's looking after you work thru Caitlin and my suggestions! Looking forward to seeing that R markdown file (the 'knitted' pdf-like doc we started) develop!

**Comment by emilykelman** [comment]
Thank you! Here's where I'm at now:

testfig <- ggplot(subset( CWM_figures, trait_name%in% c("final_height_cm", "RMR", "SLA", "RDMC", "seed_mass")), mapping = aes(x=spei_12, y=value))+
  geom_point(aes(col = transect_ID), size = 0.5)+
  facet_grid(trait_name~., scales = "free_y") 

I'm not sure how to specify spei_12 on the x-axis because spei_12 isn't its own object, and when I try the code above that's the error message that I get. I tried x=trait_name %in% "spei_12", y=value which gave me a figure that showed FALSE on the x-axis.

**Comment by caitlintwhite** [comment]
Hm.. so if you want spei_12 on the x axis, then make sure it's not in the trait_name column. It has to be in its own column so you can plot all the traits against it. When you gather the traits into the trait_name columns, just don't include spei_12 in that. Make sense? It sounds like this might be the reason your code is not working.

**Comment by julieelarson** [comment]
Ah, yes -- so your code looked like this in your first panel plot because you were plotting the traits AND spei over time (time was the x axis, and spei was just another y-axis variable).  So now that spei is your x-variable, we don't want it in that trait-names column, just as Caitlin described.

**Comment by caitlintwhite** [comment]
@emilykelman since I was updating scripts to read in the cleaned bos datasets and the CWV and CWM data tables generated from them, I added a line in this script to show you one way to resolve your plotting issue. I re-joined the climate data with your CWM long-format data frame so each climate variable is in its own colum. Now you can plot spei_12 against whichever traits you want.

It's a little messy because climate variables are in the "trait_name" column and in their own, but it doesn't hurt anything. It makes the data frame a little more flexible so you can plot climate variables within your panel (e.g. when time is on the x axis), or you can make a trait panel figure using one of the climate variables on the x-axis now.

When you look over the code, if all makes sense to you, then go ahead and close this issue. If it doesn't make sense, reply to let Julie and I know.

**Comment by emilykelman** [comment]
Question: I'm trying to create a panel plot of CWV and spei_12 using the pooled data, and I think in order to do that I have to create a long version where the traits are included in a "trait_name" column. I tried to do that in the CWM & CWV models script (line 44) and although I was able to create a singular column that includes all the traits, I'm not sure the corresponding "value" column is correct. I was using this as a reference, but I'm confused about what I'm supposed to enter for value. 

Function:       gather(data, key, value, ..., na.rm = FALSE, convert = FALSE)
Same as:        data %>% gather(key, value, ..., na.rm = FALSE, convert = FALSE)

Arguments:
        data:           data frame
        key:            column name representing new variable
        value:          column name representing variable values
        ...:            names of columns to gather (or not gather)
        na.rm:          option to remove observations with missing values (represented by NAs)
        convert:        if TRUE will automatically convert values to logical, integer, numeric, complex or factor as appropriate

**Comment by caitlintwhite** [comment]
Hm.. I don't see your edits in line 44 of the CWM & CWV models.R script (have you not pushed yet?). So while I can't be specific, some general comments that might help:

- the "key" term is the name of the column that will store the names of all the columns you're collapsing (e.g. "trait_name" stores values of all the column names that were previously spread out)
- the "value" term is the *name* you're giving to the column that will store all the cell values that were previously in each column (e.g. i think we just called this "value".. not being too creative :])
- what comes after that, the "...", are the names of all the columns (in wide-format) that you want to collapse together. so in your case, i think that would be all the traits/CWMs/CWVs, and don't include spei_12 in there if you want to plot it on the x axis... **OR** you can include the climate variables in the columns you're collapsing, in case you want to show everything over time, and then left_join the climate dataset back in by "year" (like how I did for the transect data frame". choose your own adventure!

try it out and let us know if you figure it out or need more help (go emily! woooo!!!).

**Comment by emilykelman** [comment]
I pushed the edits right after I commented on the issue, whoops. The edit on line 44 should be there now.  Thank you for the clarifications Caitlin! I think I created the DF correctly...now on to creating the CWV panel plots
