### ISSUE TITLE
Trying to subset vegetative cover data 

### ISSUE THREAD

**Issue by emilykelman** [caitlintwhite/KelmanProject#5]
I can't figure out how to remove "litter", "rock", "standing dead", and "baregd" out of the OSMP_Code  column in order to find the new relative vegetative cover. I can remove one, but as soon as I add another it won't recognize my code.

**Comment by julieelarson** [comment]
Hi Emily, I know we were struggling to remove all the terms in one line of code. There are a couple other options:

1) Remove one type of row at a time, successively. So for example, to remove all the litter rows, then take that new dataframe and remove all the rock rows, etc:

vegcoverdat <- subset(cover_dat, !OSMP_Code == c("rock"))
vegcoverdat <- subset(vegcoverdat, !OSMP_Code == c("litter"))

The key is that once you create the new dataframe 'vegcoverdat' in the first line, you have to make sure you are subsetting from that data frame in each subsequent line.

2) The 'filter' function in the dplyer package is another way to subset a dataframe. I tried it out and it seems more flexible to subset out multiple things at once. You could try this code:

# Create an object to store the terms you want to remove
remove <- c("rock","litter","baregd","standing dead")
# Filter the dataframe 'cover_dat' to include only rows that do NOT have these terms under OSMP_Code
vegcoverdat <- cover_dat %>%
  filter(!OSMP_Code %in% remove)

**Comment by caitlintwhite** [comment]
Can also subset bos veg data to select for Lifeform != "Ground cover".

Think this has been resolved by now so closing issue.
