### ISSUE TITLE
cover7_1 object not found, line 79, bos_cwm_and_climate R script 

### ISSUE THREAD

**Issue by emilykelman** [caitlintwhite/KelmanProject#8]
line 79 on the explore bos_cwm_and_climate script: object 'cover7_1 not found. I replaced it with "bos_dat" because I think that's the data frame we're looking at in order to compare the species names in each dataset..but either way was trying to remember where the "cover7_1" object comes in and if I replaced it with the right one?

**Comment by caitlintwhite** [comment]
I'm not seeing the object "cover7_1" anywhere in the current code. Is it possible you have an older version of the script you're using? I cleaned up that script prior to pushing so all objects are general (e.g. no site-specific data frames), so code in there shouldn't be trying to run anything on "cover7_1".

Maybe trying pulling down the repo again to make sure you have the most current version of the code?
